import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="max-w-2xl mx-auto grid min-h-[100dvh] grid-rows-[1fr_auto] place-items-center">
      {children}
    </main>
  );
}
